name: Update Gradle Wrapper

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none


jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          title: "Update Gradle wrapper"
          commit-message: "Update Gradle wrapper"
          branch-suffix: timestamp
